{% set name = "pymatting" %}
{% set version = "1.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75e2ec1e346dbd564c9a2cc8229b134ec939f49008fa570025db30003d0c46fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numba !=0.49.0
    - numpy >=1.16.0
    - pillow >=5.2.0
    - scipy >=1.1.0

test:
  imports:
    - pymatting
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pymatting.github.io
  summary: Python package for alpha matting.
  dev_url: https://github.com/pymatting/pymatting
  license: MIT
  # PR made upstream to bundle in LICENSE
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - '99991'
    - tuelwer
    - thewchan
