{% set name = "pymatting" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMatting-{{ version }}.tar.gz
  sha256: a73508ef0874996831dfd284e3bc63151a09484d789fd10edc03f49b31532acc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - numba !=0.49.0
    - numpy >=1.16.0
    - pillow >=5.2.0
    - python >=3.0
    - scipy >=1.1.0

test:
  imports:
    - pymatting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pymatting.github.io
  summary: Python package for alpha matting.
  dev_url: https://github.com/pymatting/pymatting
  license: MIT
  # PR made upstream to bundle in LICENSE
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - 99991
    - tuelwer
    - thewchan
